Given a NumPy array of continuous features and a NumPy array of categorical labels, normalize the features using Standardization (Z-score) and convert the labels to a one-hot encoded matrix using 0 Python loops.

In [1]:
# --- Cell 1: Data Preprocessing ---
import numpy as np

# Dummy data: 5 samples, 3 continuous features
X_raw = np.array([[10.0, 2.0, 50.0],
                  [20.0, 4.0, 100.0],
                  [10.0, 2.0, 50.0],
                  [30.0, 6.0, 150.0],
                  [40.0, 8.0, 200.0]])

# Dummy labels: 5 samples, 3 categories (0, 1, 2)
y_raw = np.array([0, 2, 1, 0, 2])

# 1. Normalization (Z-score: (X - mean) / std)
# axis=0 calculates mean/std for each column (feature) independently
X_mean = np.mean(X_raw, axis=0)
X_std = np.std(X_raw, axis=0)
X_normalized = (X_raw - X_mean) / X_std

# 2. One-Hot Encoding WITHOUT loops
# The magic trick: np.eye(N) creates an NxN identity matrix. 
# Indexing it with your labels array instantly maps it to one-hot vectors!
num_classes = np.max(y_raw) + 1
y_one_hot = np.eye(num_classes)[y_raw]

print("Normalized X:\n", X_normalized)
print("One-Hot y:\n", y_one_hot)

Normalized X:
 [[-1.02899151 -1.02899151 -1.02899151]
 [-0.17149859 -0.17149859 -0.17149859]
 [-1.02899151 -1.02899151 -1.02899151]
 [ 0.68599434  0.68599434  0.68599434]
 [ 1.54348727  1.54348727  1.54348727]]
One-Hot y:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


- Custom Metrics in NumPy (Precision & Recall)
Professor's Hint: "Some metrics... require implementing a metric using NumPy [without loops]"

- Task: Calculate Precision and Recall for a binary classification task using raw thresholded predictions and true labels, using only NumPy array operations.

In [ ]:


# Dummy data: 0 is Negative, 1 is Positive
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0])
y_pred = np.array([1, 0, 1, 0, 0, 1, 1, 0]) # Model predictions

# Calculate True Positives, False Positives, and False Negatives using vectorization
# (y_true == 1) & (y_pred == 1) returns a boolean array. sum() counts the Trues.
TP = np.sum((y_true == 1) & (y_pred == 1))
FP = np.sum((y_true == 0) & (y_pred == 1))
FN = np.sum((y_true == 1) & (y_pred == 0))

# Precision: TP / (TP + FP)
precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0

# Recall: TP / (TP + FN)
recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Precision: 0.7500
Recall: 0.7500
